// GENERATED by scripts/gen-filter-config.mjs — do not edit by hand.
// Source: the Experience Builder filter widgets captured in
// RESST-migration/07-assessment/filter-config-extracted.json.
// Regenerate with: node scripts/gen-filter-config.mjs

import type { FilterDef } from "../filters/engine";

export const FILTER_DEFS: FilterDef[] = [
  {
    "key": "sites.site_name",
    "domain": "sites",
    "field": "site_name",
    "label": "Site Name",
    "match": "exact",
    "dynamic": true
  },
  {
    "key": "sites.responsible_districtagency",
    "domain": "sites",
    "field": "responsible_districtagency",
    "label": "Responsible Group",
    "match": "contains",
    "dynamic": true
  },
  {
    "key": "sites.sediment_release",
    "domain": "sites",
    "field": "sediment_release",
    "label": "Sediment Release",
    "match": "contains",
    "options": [
      "Drawdown",
      "Water Injection Dredging",
      "Dam Removal",
      "Diversion",
      "Normal Operation",
      "Hydraulic Dredging",
      "Dredging"
    ]
  },
  {
    "key": "sites.ecological_concern",
    "domain": "sites",
    "field": "ecological_concern",
    "label": "Ecological Concern",
    "match": "contains",
    "options": [
      "Fish Passage",
      "Spawning",
      "Water Quality",
      "Biological Opinion",
      "Endangered Species"
    ]
  },
  {
    "key": "sites.site_type",
    "domain": "sites",
    "field": "site_type",
    "label": "Site Type",
    "match": "contains",
    "options": [
      "Flood Control",
      "Dry Dam",
      "Sediment Control",
      "River Training Dike",
      "Water supply",
      "Hydropower",
      "Riffle"
    ]
  },
  {
    "key": "sites.analysis",
    "domain": "sites",
    "field": "analysis",
    "label": "Analysis",
    "match": "contains",
    "options": [
      "1D Unsteady Sediment",
      "Field Monitoring",
      "2D Sediment",
      "Hydraulic",
      "3D Sediment"
    ]
  },
  {
    "key": "siteLit.document_type",
    "domain": "siteLit",
    "field": "document_type",
    "label": "Document Type",
    "match": "contains",
    "options": [
      "ERDC TN",
      "Government Report",
      "Journal Article",
      "Thesis",
      "USACE Report",
      "Design Manual",
      "Book",
      "Conference Paper",
      "USGS Report"
    ]
  },
  {
    "key": "siteLit.purpose",
    "domain": "siteLit",
    "field": "purpose",
    "label": "Purpose",
    "match": "contains",
    "options": [
      "Planning",
      "Design",
      "Construction",
      "Operations",
      "Maintenance",
      "Reporting",
      "Analysis"
    ]
  },
  {
    "key": "siteLit.data_collection",
    "domain": "siteLit",
    "field": "data_collection",
    "label": "Data Collection",
    "match": "contains",
    "options": [
      "Bathymetry",
      "Water Quality",
      "Sediment",
      "Ecological",
      "Public Participation",
      "Hydraulics"
    ]
  },
  {
    "key": "siteLit.modeling",
    "domain": "siteLit",
    "field": "modeling",
    "label": "Modeling",
    "match": "contains",
    "options": [
      "Hydraulic Equations",
      "Hydraulic Modeling",
      "Ecological Modeling",
      "Laboratory Analysis",
      "Sediment Transport_Modeling",
      "Frequency Analysis",
      "Regression"
    ]
  },
  {
    "key": "siteLit.adaptive_management",
    "domain": "siteLit",
    "field": "adaptive_management",
    "label": "Adaptive Management",
    "match": "contains",
    "options": [
      "Flood_risk",
      "Economics",
      "Watershed planning",
      "Maintenance",
      "Operations"
    ]
  },
  {
    "key": "siteLit.sediment_characteristic",
    "domain": "siteLit",
    "field": "sediment_characteristic",
    "label": "Sediment Characteristic",
    "match": "contains",
    "options": [
      "Cohesive",
      "Gravel",
      "Sand",
      "Suspended",
      "Rock",
      "Bedload",
      "Flocculation",
      "Woody Particle",
      "Silt",
      "Clay"
    ]
  },
  {
    "key": "siteLit.sediment_source",
    "domain": "siteLit",
    "field": "sediment_source",
    "label": "Sediment Source",
    "match": "contains",
    "options": [
      "Bank erosion",
      "Headcut",
      "Reservoir pool",
      "Reservoir release",
      "Suspended",
      "Debris",
      "Erosion",
      "Emergency Spillway",
      "Plunge Pool",
      "Dredging"
    ]
  },
  {
    "key": "siteLit.covered_topics_ecohydrology",
    "domain": "siteLit",
    "field": "covered_topics_ecohydrology",
    "label": "Ecohydrology",
    "match": "exact",
    "dynamic": true
  },
  {
    "key": "siteLit.covered_topics_ecohydraulics",
    "domain": "siteLit",
    "field": "covered_topics_ecohydraulics",
    "label": "Ecohydraulics",
    "match": "exact",
    "dynamic": true
  },
  {
    "key": "siteLit.covered_topics_ecological_systems",
    "domain": "siteLit",
    "field": "covered_topics_ecological_systems",
    "label": "Ecological Systems Assessed",
    "match": "exact",
    "dynamic": true
  },
  {
    "key": "siteLit.covered_topics_future_conditions",
    "domain": "siteLit",
    "field": "covered_topics_future_conditions",
    "label": "Future Conditions",
    "match": "exact",
    "dynamic": true
  },
  {
    "key": "siteLit.risk_and_uncertainty",
    "domain": "siteLit",
    "field": "risk_and_uncertainty",
    "label": "Risk and Uncertainty",
    "match": "contains",
    "options": [
      "Flood",
      "Drought",
      "Structure failure",
      "Adaptive management"
    ]
  },
  {
    "key": "siteLit.special_cases",
    "domain": "siteLit",
    "field": "special_cases",
    "label": "Special Cases",
    "match": "contains",
    "options": [
      "Debris flow",
      "Wildfire",
      "Ice",
      "Landslide",
      "Earthquake",
      "Volcanos"
    ]
  },
  {
    "key": "siteLit.geography",
    "domain": "siteLit",
    "field": "geography",
    "label": "Geography",
    "match": "contains",
    "dynamic": true
  },
  {
    "key": "siteLit.sustainable_sediment_management",
    "domain": "siteLit",
    "field": "sustainable_sediment_management",
    "label": "Sustainable Sed Mgmt",
    "match": "contains",
    "options": [
      "Sediment release",
      "Dam removal",
      "Land management",
      "Beneficial use of dredged_materials",
      "Flood diversion",
      "Silt dams",
      "Deposition control",
      "NA"
    ]
  },
  {
    "key": "siteLit.land_use",
    "domain": "siteLit",
    "field": "land_use",
    "label": "Land Use",
    "match": "contains",
    "options": [
      "Urban",
      "Forestry",
      "Multi-use",
      "Upland",
      "Island",
      "Wetlands",
      "Beach",
      "Lowland",
      "Agriculture"
    ]
  },
  {
    "key": "siteLit.channel_type",
    "domain": "siteLit",
    "field": "channel_type",
    "label": "Channel Type",
    "match": "exact",
    "options": [
      "Mountain torrents",
      "Alluvial fans",
      "Braided rivers",
      "Arroyos",
      "Meandering rivers",
      "Modified streams",
      "Regulated rivers",
      "Deltas",
      "Underfit streams",
      "Cohesive channels"
    ]
  },
  {
    "key": "generalLit.document_type",
    "domain": "generalLit",
    "field": "document_type",
    "label": "Document Type",
    "match": "contains",
    "options": [
      "ERDC TN",
      "Government Report",
      "Journal Article",
      "Thesis",
      "USACE Report",
      "Design Manual",
      "Book",
      "Conference Paper",
      "USGS Report"
    ]
  },
  {
    "key": "generalLit.purpose",
    "domain": "generalLit",
    "field": "purpose",
    "label": "Purpose",
    "match": "contains",
    "options": [
      "Planning",
      "Design",
      "Construction",
      "Maintenance",
      "Reporting",
      "Analysis"
    ]
  },
  {
    "key": "generalLit.data_collection",
    "domain": "generalLit",
    "field": "data_collection",
    "label": "Data Collection",
    "match": "contains",
    "options": [
      "Bathymetry",
      "Water Quality",
      "Sediment",
      "Ecological",
      "Public Participation",
      "Hydraulics"
    ]
  },
  {
    "key": "generalLit.modeling",
    "domain": "generalLit",
    "field": "modeling",
    "label": "Modeling",
    "match": "contains",
    "options": [
      "Hydraulic Equations",
      "Hydraulic Modeling",
      "Ecological Modeling",
      "Laboratory Analysis",
      "Sediment Transport_Modeling",
      "Frequency Analysis",
      "Regression"
    ]
  },
  {
    "key": "generalLit.adaptive_management",
    "domain": "generalLit",
    "field": "adaptive_management",
    "label": "Adaptive Management",
    "match": "contains",
    "options": [
      "Flood_risk",
      "Economics",
      "Watershed planning",
      "Maintenance",
      "Operations"
    ]
  },
  {
    "key": "generalLit.sediment_characteristic",
    "domain": "generalLit",
    "field": "sediment_characteristic",
    "label": "Sediment Characteristic",
    "match": "contains",
    "options": [
      "Cohesive",
      "Gravel",
      "Sand",
      "Suspended",
      "Rock",
      "Bedload",
      "Flocculation",
      "Woody Particle",
      "Silt",
      "Clay"
    ]
  },
  {
    "key": "generalLit.sediment_source",
    "domain": "generalLit",
    "field": "sediment_source",
    "label": "Sediment Source",
    "match": "contains",
    "options": [
      "Bank erosion",
      "Headcut",
      "Reservoir pool",
      "Reservoir release",
      "Suspended",
      "Debris",
      "Erosion",
      "Emergency Spillway",
      "Plunge Pool",
      "Dredging"
    ]
  },
  {
    "key": "generalLit.covered_topics_ecohydrology",
    "domain": "generalLit",
    "field": "covered_topics_ecohydrology",
    "label": "Ecohydrology",
    "match": "exact",
    "dynamic": true
  },
  {
    "key": "generalLit.covered_topics_ecohydraulics",
    "domain": "generalLit",
    "field": "covered_topics_ecohydraulics",
    "label": "Ecohydraulics",
    "match": "exact",
    "dynamic": true
  },
  {
    "key": "generalLit.covered_topics_ecological_systems",
    "domain": "generalLit",
    "field": "covered_topics_ecological_systems",
    "label": "Ecological Syst Assessed",
    "match": "exact",
    "dynamic": true
  },
  {
    "key": "generalLit.covered_topics_future_conditions",
    "domain": "generalLit",
    "field": "covered_topics_future_conditions",
    "label": "Future Conditions",
    "match": "exact",
    "dynamic": true
  },
  {
    "key": "generalLit.risk_and_uncertainty",
    "domain": "generalLit",
    "field": "risk_and_uncertainty",
    "label": "Risk and Uncertainty",
    "match": "contains",
    "options": [
      "Flood",
      "Drought",
      "Structure failure",
      "Adaptive management"
    ]
  },
  {
    "key": "generalLit.special_cases",
    "domain": "generalLit",
    "field": "special_cases",
    "label": "Special Cases",
    "match": "contains",
    "options": [
      "Debris flow",
      "Wildfire",
      "Ice",
      "Landslide",
      "Earthquake",
      "Volcanos"
    ]
  },
  {
    "key": "generalLit.geography",
    "domain": "generalLit",
    "field": "geography",
    "label": "Geography",
    "match": "contains",
    "dynamic": true
  },
  {
    "key": "generalLit.sustainable_sediment_management",
    "domain": "generalLit",
    "field": "sustainable_sediment_management",
    "label": "Sustainable Sediment Mgmt",
    "match": "contains",
    "options": [
      "Sediment release",
      "Dam removal",
      "Land management",
      "Beneficial use of dredged_materials",
      "Flood diversion",
      "Silt dams",
      "Deposition control",
      "NA"
    ]
  },
  {
    "key": "generalLit.land_use",
    "domain": "generalLit",
    "field": "land_use",
    "label": "Land Use",
    "match": "contains",
    "options": [
      "Urban",
      "Forestry",
      "Multi-use",
      "Upland",
      "Island",
      "Wetlands",
      "Beach",
      "Lowland",
      "Agriculture"
    ]
  },
  {
    "key": "generalLit.channel_type",
    "domain": "generalLit",
    "field": "channel_type",
    "label": "Channel Type",
    "match": "contains",
    "options": [
      "Mountain torrents",
      "Alluvial fans",
      "Braided rivers",
      "Arroyos",
      "Meandering rivers",
      "Modified streams",
      "Regulated rivers",
      "Deltas",
      "Underfit streams",
      "Cohesive channels"
    ]
  }
];
