// GENERATED by scripts/gen-content.mjs — do not edit by hand.
// Source: the archived Experience Builder config (bookmark widget_185,
// help section views) and web map. Regenerate: node scripts/gen-content.mjs

export interface MapViewDef {
  id: string;
  name: string;
  /** [west, south, east, north] in lon/lat. */
  bounds: [number, number, number, number];
  overlays: Record<string, boolean>;
  thumb: string | null;
}

export const MAP_VIEWS: MapViewDef[] = [
  {
    "id": "default",
    "name": "Default",
    "bounds": [
      -116.7544,
      30.8881,
      -79.9282,
      46.6079
    ],
    "overlays": {
      "nid": false,
      "gauges": false,
      "ssurgo": false,
      "rivers": false,
      "huc2": false,
      "huc4": false,
      "huc6": false,
      "huc8": false
    },
    "thumb": "views/widget_185-snap6-1754535899512.jpg"
  },
  {
    "id": "usgs-huc2",
    "name": "USGS HUC2",
    "bounds": [
      -116.7544,
      30.8881,
      -79.9282,
      46.6079
    ],
    "overlays": {
      "nid": false,
      "gauges": false,
      "ssurgo": false,
      "rivers": false,
      "huc2": true,
      "huc4": false,
      "huc6": false,
      "huc8": false
    },
    "thumb": "views/widget_185-snap1-1754535919417.jpg"
  },
  {
    "id": "usgs-huc4",
    "name": "USGS HUC4",
    "bounds": [
      -116.7544,
      30.8881,
      -79.9282,
      46.6079
    ],
    "overlays": {
      "nid": false,
      "gauges": false,
      "ssurgo": false,
      "rivers": false,
      "huc2": false,
      "huc4": true,
      "huc6": false,
      "huc8": false
    },
    "thumb": "views/widget_185-snap2-1754535922924.jpg"
  },
  {
    "id": "usgs-huc6",
    "name": "USGS HUC6",
    "bounds": [
      -116.7544,
      30.8881,
      -79.9282,
      46.6079
    ],
    "overlays": {
      "nid": false,
      "gauges": false,
      "ssurgo": false,
      "rivers": false,
      "huc2": false,
      "huc4": false,
      "huc6": true,
      "huc8": false
    },
    "thumb": "views/widget_185-snap4-1754535925941.jpg"
  },
  {
    "id": "usgs-huc8",
    "name": "USGS HUC8",
    "bounds": [
      -116.7544,
      30.8881,
      -79.9282,
      46.6079
    ],
    "overlays": {
      "nid": false,
      "gauges": false,
      "ssurgo": false,
      "rivers": false,
      "huc2": false,
      "huc4": false,
      "huc6": false,
      "huc8": true
    },
    "thumb": "views/widget_185-snap5-1754535929354.jpg"
  },
  {
    "id": "rivers",
    "name": "Rivers",
    "bounds": [
      -116.7544,
      30.8881,
      -79.9282,
      46.6079
    ],
    "overlays": {
      "nid": false,
      "gauges": false,
      "ssurgo": false,
      "rivers": true,
      "huc2": false,
      "huc4": false,
      "huc6": false,
      "huc8": false
    },
    "thumb": "views/widget_185-snap3-1754535934084.jpg"
  }
];
